[workspace]
resolver = "3"
members = [
    "crates/edvige-imap",
]

[workspace.dependencies]
anyhow = "1"
nom = "8.0"
rustls = "0.23"
thiserror = "2"
tokio = { version = "1.50", features = ["full"] }
tokio-rustls = "0.26"
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
webpki-roots = "1"
